version: '3'
services:
  backend:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 80:80
